#!/bin/bash
#
# gen-ldap.sh - Generate LDIF from passwd and pubkeys
#
# DESCRIPTION:
#   This script generates LDIF files from passwd file and pubkeys directory
#   for LDAP user provisioning. The output can be imported into OpenLDAP
#   using ldapadd.
#
# USAGE:
#   ./gen-ldap.sh <base_dn> [passwd_file] [pubkeys_dir] [output_file]
#
# PARAMETERS:
#   base_dn      - LDAP base DN (required), e.g., "dc=lab,dc=example,dc=edu"
#   passwd_file  - Path to passwd file (default: ./passwd)
#   pubkeys_dir  - Path to pubkeys directory (default: ./pubkeys)
#   output_file  - Output LDIF file (default: ./users.ldif)
#
# EXAMPLE:
#   ./gen-ldap.sh "dc=lab,dc=edu"
#   ./gen-ldap.sh "dc=lab,dc=edu" /tmp/passwd /tmp/pubkeys /tmp/users.ldif
#
# OBJECTCLASSES:
#   - inetOrgPerson  - structural class (cn, sn, uid)
#   - posixAccount   - auxiliary class (uidNumber, gidNumber, homeDirectory, loginShell)
#   - ldapPublicKey  - auxiliary class (sshPublicKey, requires openssh-lpk schema)
#
# SEE ALSO:
#   export-users.sh  - Export regular users to passwd file
#   export-pubkeys.sh - Export SSH public keys from user directories
#

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Parse command line arguments
BASE_DN="${1:-}"
PASSWD_FILE="${2:-$SCRIPT_DIR/passwd}"
PUBKEYS_DIR="${3:-$SCRIPT_DIR/pubkeys}"
OUTPUT_FILE="${4:-$SCRIPT_DIR/users.ldif}"

# Validate required parameters
if [ -z "$BASE_DN" ]; then
  echo "Error: base_dn is required"
  echo "Usage: $0 <base_dn> [passwd_file] [pubkeys_dir] [output_file]"
  echo "Example: $0 \"dc=lab,dc=example,dc=edu\""
  exit 1
fi

# Check if passwd file exists
if [ ! -f "$PASSWD_FILE" ]; then
  echo "Error: passwd file not found at $PASSWD_FILE"
  exit 1
fi

# Check if pubkeys directory exists (warning only, not fatal)
if [ ! -d "$PUBKEYS_DIR" ]; then
  echo "Warning: pubkeys directory not found at $PUBKEYS_DIR"
  echo "Users will be created without sshPublicKey attribute"
fi

# Function to extract surname from gecos field
# Takes full name like "John Doe" and returns "Doe"
# Falls back to username if gecos is empty or has no spaces
extract_surname() {
  local gecos="$1"
  local username="$2"

  # Remove everything after first comma (phone, room, etc.)
  local name="${gecos%%,*}"

  # If empty, use username
  if [ -z "$name" ]; then
    echo "$username"
    return
  fi

  # Get last word as surname
  local surname="${name##* }"

  # If same as full name (single word), use it as surname
  if [ -z "$surname" ]; then
    echo "$name"
  else
    echo "$surname"
  fi
}

# Function to extract cn (common name) from gecos field
extract_cn() {
  local gecos="$1"
  local username="$2"

  # Remove everything after first comma
  local name="${gecos%%,*}"

  # If empty, use username
  if [ -z "$name" ]; then
    echo "$username"
  else
    echo "$name"
  fi
}

# Write LDIF header
{
  echo "# LDIF generated by gen-ldap.sh"
  echo "# Base DN: $BASE_DN"
  echo "# Source: $PASSWD_FILE"
  echo "# Generated: $(date -Iseconds)"
  echo ""
} > "$OUTPUT_FILE"

# Process each user in passwd file
user_count=0
while IFS=: read -r username _password uid gid gecos home shell; do
  # Skip users with UID < 1000 (system users)
  if [ "$uid" -lt 1000 ] 2> /dev/null; then
    continue
  fi

  # Extract cn and sn from gecos
  cn=$(extract_cn "$gecos" "$username")
  sn=$(extract_surname "$gecos" "$username")

  # Write LDIF entry
  {
    echo "dn: uid=$username,ou=People,$BASE_DN"
    echo "objectClass: inetOrgPerson"
    echo "objectClass: posixAccount"
    echo "objectClass: ldapPublicKey"
    echo "uid: $username"
    echo "cn: $cn"
    echo "sn: $sn"
    echo "uidNumber: $uid"
    echo "gidNumber: $gid"
    echo "homeDirectory: $home"
    echo "loginShell: $shell"

    # Add sshPublicKey if key file exists
    pubkey_file="$PUBKEYS_DIR/$username"
    if [ -f "$pubkey_file" ]; then
      # Read each line of the pubkey file (may contain multiple keys)
      while IFS= read -r key || [ -n "$key" ]; do
        if [ -n "$key" ]; then
          echo "sshPublicKey: $key"
        fi
      done < "$pubkey_file"
    fi

    echo ""
  } >> "$OUTPUT_FILE"

  user_count=$((user_count + 1))
done < "$PASSWD_FILE"

echo "Generated $OUTPUT_FILE with $user_count user(s)"
